Test reports

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -22,7 +22,7 @@ jobs:
           - java: 17
             sonar: false
     name: Build
-    if: github.repository == 'sixhours-team/memcached-spring-boot'
+#    if: github.repository == 'sixhours-team/memcached-spring-boot'
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -46,10 +46,16 @@ jobs:
         run: |
           echo "Build Branch => Branch [$GITHUB_REF_NAME]"
           ./gradlew build
-      - name: Run code analysis
-        if: ${{ matrix.sonar && github.event_name != 'pull_request'}}
-        run: |
-          echo "Run SonarQube Analysis => Branch [$GITHUB_REF_NAME]"
-          ./gradlew sonarqube -Dsonar.verbose=true --stacktrace
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      - name: Publish test report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          check_name: Test results (${{ matrix.java }})
+          report_paths: memcached-spring-boot-autoconfigure/build/test-results/**/TEST-*.xml
+#      - name: Run code analysis
+#        if: ${{ matrix.sonar && github.event_name != 'pull_request'}}
+#        run: |
+#          echo "Run SonarQube Analysis => Branch [$GITHUB_REF_NAME]"
+#          ./gradlew sonarqube -Dsonar.verbose=true --stacktrace
+#        env:
+#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
